### ISSUE TITLE
Policy for pkg updates

### ISSUE THREAD

**Issue by asvc** [vedetta-com/caesonia#225]
Hypothetical scenario: User installs OpenBSD and follows Caesonia guide to setup a mail server. 
Week later, CVE is discovered in one of the components that are not part of the OpenBSD distribution and therefore not updated in `stable`. 

What is the best mitigation from user's standpoint? Quick search shows only M:Tier, company operating within UK legal framework, or running `-current` branch whis is as per official FAQ:

> Make sure you've read and understand how to build the system from source before using -current

Recent examples:
- https://nvd.nist.gov/vuln/detail/CVE-2019-11494
- https://nvd.nist.gov/vuln/detail/CVE-2019-11499

https://www.mtier.org/contact/
     Company Registration No. 06569719
     VAT Registration No. 932 2624 41

**Comment by horia** [comment]
On `-current` base it's easy, because there are fresh packages created from the `-current` ports tree in the official pkg repository.

On `-release` base, we have two options:
1) use the `-stable` ports tree to build ports with security backports
2) backport the needed port(s) from the `-current` ports tree to the `-stable` ports tree

> When serious bugs or security flaws are discovered in third party software, they are fixed in the -stable branch of the ports tree. In contrast to the base system, the -stable ports tree only gets security backports for the latest release. --[Security Updates (-stable)](https://www.openbsd.org/faq/ports/ports.html#PortsSecurity)

For creating packages used by caesonia, I'm using a 1GB RAM machine with 2.00GHz CPU (preferably offline) with [proot(1)](https://man.openbsd.org/proot) and `FETCH_PACKAGES=yes` in [mk.conf(5)](https://man.openbsd.org/mk.conf)

More information about getting the ports trees in [Anonymous CVS](https://www.openbsd.org/anoncvs.html) FAQ

For the second option, to backport from the `-current` ports tree, get the needed port (and its updated dependencies, if desired) in "mystuff" (add `PORTSDIR_PATH=${PORTSDIR}/mystuff:${PORTSDIR}` to mk.conf) e.g.
```sh
cd /usr/ports/mystuff/mail
cvs -d anoncvs@anoncvs.ca.openbsd.org:/cvs checkout -d rspamd -P ports/mail/rspamd
```

Build the port (and its updated dependencies,) and create a package
```sh
make -C rspamd fake package
```

Sign packages
```sh
cd /var/ports/packages/amd64
pkg_sign -s signify2 -s /etc/signify/caesonia-pkg.sec -o signed -S all/
```

Install the package on the email service host
```sh
pkg_add https://example.com/pub/OpenBSD/6.5/packages/amd64/rspamd-1.9.4.tgz
```

Revise software configuration, since `-current` ports tree has major version updates.

p.s. don't build ports as `root`

**Comment by asvc** [comment]
So OpenBSD has concept of `backports` similar to Debian. I've learned something new today, thanks!
